INSERT INTO properties (code, name, unit) VALUES ('agent_free', 'Комиссия агента', '%');
INSERT INTO properties (code, name, unit) VALUES ('apartment', 'Номер квартиры', null);
INSERT INTO properties (code, name, unit) VALUES ('balcony', 'Балкон', null);
INSERT INTO properties (code, name, unit) VALUES ('bathroom_type', 'Санузел', null);
INSERT INTO properties (code, name, unit) VALUES ('build_year', 'Год постройки', 'г.');
INSERT INTO properties (code, name, unit) VALUES ('ceiling_height', 'Высота потолков', 'м');
INSERT INTO properties (code, name, unit) VALUES ('floor', 'Этаж', null);
INSERT INTO properties (code, name, unit) VALUES ('floors_total', 'Всего этажей', null);
INSERT INTO properties (code, name, unit) VALUES ('garage_building_type', 'Материал', null);
INSERT INTO properties (code, name, unit) VALUES ('garage_name', 'Название ГСК', null);
INSERT INTO properties (code, name, unit) VALUES ('garage_ownership', 'Статус', null);
INSERT INTO properties (code, name, unit) VALUES ('garage_type', 'Тип гаража', null);
INSERT INTO properties (code, name, unit) VALUES ('gross_area', 'Общая площадь', 'м²');
INSERT INTO properties (code, name, unit) VALUES ('haggle', 'Торг', null);
INSERT INTO properties (code, name, unit) VALUES ('house_type', 'Тип дома', null);
INSERT INTO properties (code, name, unit) VALUES ('kitchen_area', 'Площадь кухни', 'м²');
INSERT INTO properties (code, name, unit) VALUES ('living_area', 'Жилая площадь', 'м²');
INSERT INTO properties (code, name, unit) VALUES ('lot_area', 'Площадь участка', 'соток');
INSERT INTO properties (code, name, unit) VALUES ('lot_type', 'Тип участка', null);
INSERT INTO properties (code, name, unit) VALUES ('mortgage', 'Ипотека', null);
INSERT INTO properties (code, name, unit) VALUES ('new_building', 'Дом не сдан', null);
INSERT INTO properties (code, name, unit) VALUES ('parking', 'Парковка', null);
INSERT INTO properties (code, name, unit) VALUES ('pledge', 'Залог', null);
INSERT INTO properties (code, name, unit) VALUES ('prepayment', 'Предоплата', '%');
INSERT INTO properties (code, name, unit) VALUES ('price_period', 'Оплата за период', null);
INSERT INTO properties (code, name, unit) VALUES ('realty_type', 'Тип недвижимости', null);
INSERT INTO properties (code, name, unit) VALUES ('renovation', 'Ремонт', null);
INSERT INTO properties (code, name, unit) VALUES ('room', 'Комнат', null);
INSERT INTO properties (code, name, unit) VALUES ('rooms_area', 'Площадь комнат', null);
INSERT INTO properties (code, name, unit) VALUES ('rooms_offered', 'Комнат в сделке', null);
INSERT INTO properties (code, name, unit) VALUES ('transaction_type', 'Тип сделки', null);
INSERT INTO properties (code, name, unit) VALUES ('utilities_included', 'Коммунальные услуги входят в стоимость', null);
INSERT INTO properties (code, name, unit) VALUES ('window_view', 'Окна выходят', null);