INSERT INTO property_values (value, text, property_code) VALUES (1, '1', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (2, '2', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (3, '3', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (4, '4', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (5, '5', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (6, '6', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (7, '7+', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (8, 'Студия', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (9, 'Свободная планировка', 'room');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Кирпичный', 'house_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Монолитный', 'house_type');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Панельный', 'house_type');
INSERT INTO property_values (value, text, property_code) VALUES (4, 'Кирпично-монолитный', 'house_type');
INSERT INTO property_values (value, text, property_code) VALUES (5, 'Блочный', 'house_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Совмещенный', 'bathroom_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Раздельный', 'bathroom_type');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Два и больше', 'bathroom_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Балкон', 'balcony');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Лоджия', 'balcony');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Во двор', 'window_view');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'На улицу', 'window_view');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Дизайнерский', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (2, '«Евроремонт»', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Хороший', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (4, 'Косметический', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (5, 'Обычный', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (6, 'Требуется косметический', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (7, 'Требует ремонта', 'renovation');
INSERT INTO property_values (value, text, property_code) VALUES (1, '1', 'new_building');
INSERT INTO property_values (value, text, property_code) VALUES (1, '1', 'pledge');
INSERT INTO property_values (value, text, property_code) VALUES (1, '1', 'rooms_offered');
INSERT INTO property_values (value, text, property_code) VALUES (2, '2', 'rooms_offered');
INSERT INTO property_values (value, text, property_code) VALUES (3, '3', 'rooms_offered');
INSERT INTO property_values (value, text, property_code) VALUES (4, '4', 'rooms_offered');
INSERT INTO property_values (value, text, property_code) VALUES (5, '5', 'rooms_offered');
INSERT INTO property_values (value, text, property_code) VALUES (6, '6', 'rooms_offered');
INSERT INTO property_values (value, text, property_code) VALUES (1, '1', 'utilities_included');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'В месяц', 'price_period');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'В день', 'price_period');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'ИЖС', 'lot_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'В садоводстве', 'lot_type');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Фермерский', 'lot_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Гараж', 'garage_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Машиноместо', 'garage_type');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Бокс', 'garage_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Кирпичный', 'garage_building_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Металлический', 'garage_building_type');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Железобетонный', 'garage_building_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Собственность', 'garage_ownership');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Кооператив', 'garage_ownership');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'По доверенности', 'garage_ownership');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Продажа', 'transaction_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Аренда', 'transaction_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Квартира', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Комната', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Дом', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (4, 'Гараж или машиноместо', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (5, 'Участок', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (6, 'Офисное помещение', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (7, 'Торговое помещение', 'realty_type');
INSERT INTO property_values (value, text, property_code) VALUES (1, '1', 'haggle');
INSERT INTO property_values (value, text, property_code) VALUES (1, 'Нет парковки', 'parking');
INSERT INTO property_values (value, text, property_code) VALUES (2, 'Охраняемая парковка', 'parking');
INSERT INTO property_values (value, text, property_code) VALUES (3, 'Отдельная парковка', 'parking');
INSERT INTO property_values (value, text, property_code) VALUES (4, 'Парковка рядом', 'parking');
INSERT INTO property_values (value, text, property_code) VALUES (5, 'Подземная парковка', 'parking');